debug: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cfw?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cfw
    password: cfw
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 172.24.8.123
    database: 0
 
security:
  oauth2:
    resource:
      filter-order: 3

kaptcha:
  session:
    key: kaptcha.code
  border: no
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy
  obscurificator:
    impl: com.google.code.kaptcha.impl.ShadowGimpy #com.google.code.kaptcha.impl.WaterRipple
  #不要噪点
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise
  image:
    width: 100
    height: 30
  textproducer:
    font:
      size: 22
      color: red
      names: Arial,Courier
    char:
      length: 4
      space: 8
      string: abcefgijkmnoqrsuvwxyz13579
  #和登录框背景颜色一致
  background:
    clear:
      from: 247,247,247
      to: 247,247,247
          
  chkurl: /sys/img_code
  input:
      name: image_kaptcha

webapp:
  content_type:
    json: application/json;charset=utf-8
  pc:
    service: cn.inctech.app..*ServiceImp*
    dao: cn.inctech.app..*(Dao|Mapper)*
    