debug: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/it_talents?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: talents
    password: talents
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 172.24.8.123
    database: 0
 
security:
  oauth2:
    resource:
      filter-order: 3

kaptcha:
  session:
    key: kaptcha_session_code
  border: no
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy
  obscurificator:
    impl: com.google.code.kaptcha.impl.ShadowGimpy #com.google.code.kaptcha.impl.WaterRipple
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise
  image:
    width: 100
    height: 30
  textproducer:
    font:
      size: 22
      color: red
      names: Arial,Courier
    char:
      length: 4
      space: 8
      string: abcefgijkmnoqrsuvwxyz13579
  background:
    clear:
      from: 247,247,247
      to: 247,247,247
          
  chkurl: /sys/img_code
  input:
      name: imgcode

webapp:
  use_pageHelper: false
  use_kaptcha: false
  content_type:
    json: application/json;charset=utf-8
  pc:
    service: cn.inctech.app..*ServiceImp*
    dao: cn.inctech.app..*(Dao|Mapper)*
  security:
    jdbc:
      sql_query_user_by_name: select userid,password,true from v_user where userid =?
      sql_query_auth_by_name: select username,authority from v_userauth where username=?
      sql_query_user_by_mobile: select count(*) count from v_user where mobile=?
  sms:
    sign_name: IncTech
    template_code: SMS_142090353
  cors_allow_url: http://localhost:9999  
    